# Generated by Django 3.2 on 2023-05-30 15:22

from django.db import migrations, models
import smartEatingApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad', models.CharField(max_length=50)),
                ('tipo_peso', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('foto_perfil', models.URLField(default=smartEatingApp.models.generate_random_foto_perfil)),
                ('ingredientes', models.ManyToManyField(blank=True, to='smartEatingApp.Ingrediente')),
            ],
        ),
    ]
