version: '3'

services:
  web:
   build: .
   command: python manage.py runserver 0.0.0.0:8000
   ports:
    - "8000:8000"
   volumes:
    - ./smarteating/:/code 
   env_file:
      - .env

  db:
   image: postgres:13
   volumes: 
     - postgres_data:/var/lib/postgresql/data/
   environment:
       POSTGRES_USER: ${USER_DB}
       POSTGRES_PASSWORD: ${PASSWORD_DB}
       POSTGRES_DB: smarteating_db


volumes:
  postgres_data: